name: AWS Lambda Deployer
on:
  push:
    branches:
    - main

jobs:
  deploy_lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: npm install
        run: |
          npm ci
      - name: deploy
        run: |
          zip -r deploy.zip . -x .env .github .git
          aws lambda update-function-code --function-name=$FUNCTION_NAME --zip-file=fileb://deploy.zip
        env:
          FUNCTION_NAME: ${{ secrets.AWS_LAMBDA_FUNCTION_NAME }}